name: Lavyz.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 0.937107500853017
  saturation: 0.2077536394353956
  rhythmicContrast: 0.9617089512757957
purpose: []
